# Generated by Django 6.0.4 on 2026-04-15 18:57

import django.db.models.deletion
import dynamic_template.fields
import namedid.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Human-readable name; used with NamedID to build `named_id`.",
                        max_length=255,
                        verbose_name="label",
                    ),
                ),
                (
                    "template",
                    dynamic_template.fields.RichTextField(
                        help_text="Django template language source rendered by the `dyntpl` tag. Admin widget: set DYNAMIC_TEMPLATE_RICHTEXT_WIDGET (import path to a Widget class).",
                        verbose_name="template",
                    ),
                ),
                (
                    "named_id",
                    namedid.fields.NamedIDField(
                        blank=False,
                        max_length=255,
                        null=False,
                        source_fields=["label"],
                        unique=["content_type"],
                    ),
                ),
                (
                    "model_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="ORM field names on ``object`` (empty → all concrete DB fields). Exposed as dict keys, e.g. ``{{ object.name }}``.",
                        verbose_name="model fields",
                    ),
                ),
                (
                    "annotate_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Names of annotations to copy onto ``object`` (must already exist on the ``obj=`` instance, e.g. loaded via ``Model.objects.my_annotated_manager().get(...)``).",
                        verbose_name="annotate fields",
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extra Python names merged into ``object`` via ``getattr(instance, name)``: ``@property``, class attributes, or methods.",
                        verbose_name="fields",
                    ),
                ),
                (
                    "raw_object",
                    models.BooleanField(
                        default=False,
                        help_text="When checked, ``object`` in the template is the real model instance instead of a serialized dict. Allows calling methods, traversing relations, etc. via ``{{ object.my_method }}``.",
                        verbose_name="raw object",
                    ),
                ),
                (
                    "context_object",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Dotted path to resolve ``object`` from the parent template context (e.g. ``meeting``, ``participant.meeting``). When set, ``obj=`` is no longer required in the template tag.",
                        max_length=255,
                        verbose_name="object from context",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dynamic_templates",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
            ],
            options={
                "verbose_name": "dynamic template",
                "verbose_name_plural": "dynamic templates",
            },
        ),
        migrations.CreateModel(
            name="DynamicRelationContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manager_method",
                    models.CharField(
                        default="objects.all",
                        help_text="`manager.method` with no arguments (default `objects.all`). Example: `objects.get_with_tva`. Legacy: a single name calls `_default_manager.<name>()`.",
                        max_length=128,
                        verbose_name="manager method",
                    ),
                ),
                (
                    "filter_spec",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='``.filter()`` kwargs with **resolved** values: dotted paths from ``object``, or ``{{ }}`` / ``{% %}`` for the full render context, e.g. ``{"product_id": "pk"}``, ``{"site_id": "{{ site.pk }}"}``. Non-string JSON values are ORM literals.',
                        verbose_name="filter (from object)",
                    ),
                ),
                (
                    "filter_literal",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Static ``.filter()`` kwargs (exact ORM values, no ``object`` paths, no templates). Example: {"is_active": true, "role": "staff"}. Merged with filter (from object); object-based keys override the same key here.',
                        verbose_name="filter (literal)",
                    ),
                ),
                (
                    "model_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='ORM columns per row (empty → all concrete). Dict keys in the fragment: ``{{ row.name }}``. Example: `["id", "title"]`.',
                        verbose_name="model fields",
                    ),
                ),
                (
                    "annotate_fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Annotation aliases already on the queryset returned by ``manager_method`` (e.g. ``["n_articles"]``). This app does not call ``.annotate()`` for you.',
                        verbose_name="annotate fields",
                    ),
                ),
                (
                    "fields",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Extra Python names per row via ``getattr(obj, name)``: properties, class attrs, methods.",
                        verbose_name="fields",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Variable injected into the fragment context. Leave blank to use the related model name (lowercase, e.g. article).",
                        max_length=64,
                        verbose_name="name",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Model whose manager will be used to build the queryset.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relation_context_loaders",
                        to="contenttypes.contenttype",
                        verbose_name="related model",
                    ),
                ),
                (
                    "dynamic_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relation_contexts",
                        to="dynamic_template.dynamictemplate",
                        verbose_name="dynamic template",
                    ),
                ),
            ],
            options={
                "verbose_name": "dynamic relation context",
                "verbose_name_plural": "dynamic relation contexts",
            },
        ),
        migrations.AddIndex(
            model_name="dynamictemplate",
            index=models.Index(
                fields=["content_type", "named_id"],
                name="dynamic_tem_content_426dd1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="dynamicrelationcontext",
            constraint=models.UniqueConstraint(
                fields=("dynamic_template", "name"),
                name="dynamic_template_relation_context_name_uniq",
            ),
        ),
    ]
